// ─────────────────────────────────────────────────────────────────────────────
// mockdata/users.mock.js
// Human users + AI Authors seed data
// ─────────────────────────────────────────────────────────────────────────────

export const COMMON_PASSWORD = "Qwerty123";

export const usersData = [
  // ── Original 8 users (kept + enriched) ──────────────────────────────────
  {
    username: "aisha_writes",
    email: "aisha.writes@fakemail.com",
    fullname: "Aisha Patel",
    avatar: "https://i.pravatar.cc/300?u=aisha_writes",
    bio: "Full-stack dev & weekend poet. Writing about code, creativity, and everything in between.",
    interests: ["technology", "programming", "web-development", "creative-writing", "self-improvement"],
    isPrivate: false,
  },
  {
    username: "marco_dev",
    email: "marco.dev@fakemail.com",
    fullname: "Marco Rossi",
    avatar: "https://i.pravatar.cc/300?u=marco_dev",
    bio: "Backend engineer obsessed with distributed systems. Coffee addict.",
    interests: ["technology", "programming", "devops", "cloud-computing", "open-source"],
    isPrivate: false,
  },
  {
    username: "luna_designs",
    email: "luna.designs@fakemail.com",
    fullname: "Luna Chen",
    avatar: "https://i.pravatar.cc/300?u=luna_designs",
    bio: "UI/UX designer who codes. Passionate about accessible design and pixel-perfect interfaces.",
    interests: ["design", "web-development", "ux-research", "photography", "creative-writing"],
    isPrivate: true,
  },
  {
    username: "josh_builds",
    email: "josh.builds@fakemail.com",
    fullname: "Josh Okafor",
    avatar: "https://i.pravatar.cc/300?u=josh_builds",
    bio: "DevOps engineer building resilient infrastructure. Open source contributor.",
    interests: ["devops", "cloud-computing", "open-source", "technology", "cybersecurity"],
    isPrivate: false,
  },
  {
    username: "sara_codes",
    email: "sara.codes@fakemail.com",
    fullname: "Sara Johansson",
    avatar: "https://i.pravatar.cc/300?u=sara_codes",
    bio: "ML researcher turned blogger. Demystifying AI one article at a time.",
    interests: ["artificial-intelligence", "machine-learning", "data-science", "programming", "psychology"],
    isPrivate: false,
  },
  {
    username: "ravi_thinks",
    email: "ravi.thinks@fakemail.com",
    fullname: "Ravi Menon",
    avatar: "https://i.pravatar.cc/300?u=ravi_thinks",
    bio: "Startup founder & productivity nerd. Sharing lessons from the trenches.",
    interests: ["startups", "productivity", "self-improvement", "economics", "philosophy"],
    isPrivate: true,
  },
  {
    username: "emma_explores",
    email: "emma.explores@fakemail.com",
    fullname: "Emma Larsson",
    avatar: "https://i.pravatar.cc/300?u=emma_explores",
    bio: "Frontend developer & travel blogger. React enthusiast.",
    interests: ["web-development", "design", "travel", "photography", "programming"],
    isPrivate: false,
  },
  {
    username: "kareem_hacks",
    email: "kareem.hacks@fakemail.com",
    fullname: "Kareem Al-Farsi",
    avatar: "https://i.pravatar.cc/300?u=kareem_hacks",
    bio: "Security researcher. I break things so you don't have to.",
    interests: ["cybersecurity", "programming", "open-source", "technology", "blockchain"],
    isPrivate: false,
  },

  // ── New users ────────────────────────────────────────────────────────────
  {
    username: "zen_lifts",
    email: "zen.lifts@fakemail.com",
    fullname: "Zena Obi",
    avatar: "https://i.pravatar.cc/300?u=zen_lifts",
    bio: "Personal trainer & sports science nerd. Evidence-based fitness, no BS.",
    interests: ["fitness", "psychology", "self-improvement", "health", "data-science"],
    isPrivate: false,
  },
  {
    username: "phil_stoic",
    email: "phil.stoic@fakemail.com",
    fullname: "Philip Strauss",
    avatar: "https://i.pravatar.cc/300?u=phil_stoic",
    bio: "Amateur Stoic. Philosophy teacher. Writing about ancient wisdom for modern problems.",
    interests: ["philosophy", "psychology", "self-improvement", "creative-writing", "economics"],
    isPrivate: false,
  },
  {
    username: "nora_pixels",
    email: "nora.pixels@fakemail.com",
    fullname: "Nora Blackwell",
    avatar: "https://i.pravatar.cc/300?u=nora_pixels",
    bio: "Game developer at an indie studio. Lover of procedural generation and pixel art.",
    interests: ["game-development", "programming", "creative-writing", "artificial-intelligence", "design"],
    isPrivate: false,
  },
  {
    username: "devesh_data",
    email: "devesh.data@fakemail.com",
    fullname: "Devesh Kapoor",
    avatar: "https://i.pravatar.cc/300?u=devesh_data",
    bio: "Data engineer building pipelines at scale. Obsessed with data quality and observability.",
    interests: ["data-science", "programming", "cloud-computing", "machine-learning", "technology"],
    isPrivate: false,
  },
  {
    username: "mia_mindful",
    email: "mia.mindful@fakemail.com",
    fullname: "Mia Torres",
    avatar: "https://i.pravatar.cc/300?u=mia_mindful",
    bio: "Cognitive behavioral therapist & science writer. Bridging mental health and everyday life.",
    interests: ["psychology", "self-improvement", "philosophy", "creative-writing", "health"],
    isPrivate: true,
  },
  {
    username: "kai_quests",
    email: "kai.quests@fakemail.com",
    fullname: "Kai Nakamura",
    avatar: "https://i.pravatar.cc/300?u=kai_quests",
    bio: "RPG addict turned game critic. Narrative design, lore, and the art of meaningful choices.",
    interests: ["game-development", "creative-writing", "philosophy", "technology", "psychology"],
    isPrivate: false,
  },
  {
    username: "layla_lifehacks",
    email: "layla.lifehacks@fakemail.com",
    fullname: "Layla Hassan",
    avatar: "https://i.pravatar.cc/300?u=layla_lifehacks",
    bio: "Biohacker & productivity researcher. Tracking sleep, nutrition, and performance since 2018.",
    interests: ["fitness", "psychology", "self-improvement", "data-science", "productivity"],
    isPrivate: false,
  },
];

export const aiAuthorsData = [
  {
    name: "Synthia",
    avatar: "https://api.dicebear.com/7.x/bottts/png?seed=synthia",
    bio: "AI writing assistant specializing in technology explainers and programming tutorials.",
    writingStyle: "Clear, concise, tutorial-oriented with code examples",
    topicDomains: ["programming", "web-development", "technology", "devops"],
  },
  {
    name: "Archivist",
    avatar: "https://api.dicebear.com/7.x/bottts/png?seed=archivist",
    bio: "AI curator of deep dives into science, philosophy, and the future of humanity.",
    writingStyle: "Thoughtful, long-form, essay-style with historical references",
    topicDomains: ["artificial-intelligence", "philosophy", "psychology", "economics"],
  },
  {
    name: "PixelMind",
    avatar: "https://api.dicebear.com/7.x/bottts/png?seed=pixelmind",
    bio: "AI design critic and trend analyst. Exploring aesthetics in the digital age.",
    writingStyle: "Visual, opinionated, with design critiques and trend analysis",
    topicDomains: ["design", "ux-research", "photography", "creative-writing"],
  },
  {
    name: "PulseAI",
    avatar: "https://api.dicebear.com/7.x/bottts/png?seed=pulseai",
    bio: "AI fitness & nutrition guide powered by sports science research.",
    writingStyle: "Evidence-based, practical, data-driven with actionable takeaways",
    topicDomains: ["fitness", "psychology", "self-improvement", "data-science"],
  },
  {
    name: "QuestBot",
    avatar: "https://api.dicebear.com/7.x/bottts/png?seed=questbot",
    bio: "AI gaming analyst — dissecting mechanics, narratives, and industry trends.",
    writingStyle: "Analytical, enthusiastic, pop-culture fluent with deep dives",
    topicDomains: ["game-development", "technology", "creative-writing", "artificial-intelligence"],
  },
];
