/**
 * mockexploredata.js
 * Mock data for the Explore page.
 * Each topic has a deck card config + an array of blog post previews.
 */

export const EXPLORE_TOPICS = [
  {
    id: 'poetry',
    label: 'Poetry',
    emoji: '🪶',
    tagline: 'Words that breathe between the lines',
    icon: 'format_quote',
    bgFrom: '#9f5d8a',
    bgTo: '#d4a5c7',
    textColor: '#ffffff',
    posts: [
      {
        id: 'p1',
        title: 'Midnight in a Teacup',
        catchline: 'A meditation on warmth, solitude, and the stories we pour into small vessels.',
        author: 'Sylvia Inkworth',
        authorAvatar: 'https://i.pravatar.cc/150?img=47',
        coverImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&q=80',
        readTime: '3 min read',
        likes: 1240,
        comments: 58,
        tags: ['poetry', 'reflection'],
      },
      {
        id: 'p2',
        title: 'The Grammar of Rain',
        catchline: 'Every drop a verb. Every puddle a pause. Read the sky like a sentence.',
        author: 'Remy Okafor',
        authorAvatar: 'https://i.pravatar.cc/150?img=12',
        coverImage: 'https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?w=600&q=80',
        readTime: '4 min read',
        likes: 870,
        comments: 34,
        tags: ['poetry', 'nature'],
      },
      {
        id: 'p3',
        title: 'Blueprints for a Forgotten City',
        catchline: 'Architecture of memory — what remains when the scaffolding comes down.',
        author: 'Nadia Voss',
        authorAvatar: 'https://i.pravatar.cc/150?img=32',
        coverImage: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=600&q=80',
        readTime: '5 min read',
        likes: 612,
        comments: 27,
        tags: ['poetry', 'urban'],
      },
      {
        id: 'p4',
        title: 'Haiku for a Broken Clock',
        catchline: 'Time suspended. Six syllables to say what forever couldn\'t.',
        author: 'Koji Tanaka',
        authorAvatar: 'https://i.pravatar.cc/150?img=68',
        coverImage: 'https://images.unsplash.com/photo-1495364141860-b0d03eccd065?w=600&q=80',
        readTime: '2 min read',
        likes: 2100,
        comments: 93,
        tags: ['poetry', 'haiku'],
      },
      {
        id: 'p5',
        title: 'Love Letter to a Library',
        catchline: 'Dear shelves of whispered lives — I have come to stay.',
        author: 'Elara Books',
        authorAvatar: 'https://i.pravatar.cc/150?img=21',
        coverImage: 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=600&q=80',
        readTime: '4 min read',
        likes: 1780,
        comments: 112,
        tags: ['poetry', 'books'],
      },
    ],
  },
  {
    id: 'technology',
    label: 'Technology',
    emoji: '⚡',
    tagline: 'Tomorrow is already running in the background',
    icon: 'memory',
    bgFrom: '#2d8a8a',
    bgTo: '#5fbfb3',
    textColor: '#ffffff',
    posts: [
      {
        id: 't1',
        title: 'The Transformer That Changed Everything',
        catchline: 'Attention is all you need — and here\'s what that actually means for the rest of us.',
        author: 'Dev Patel',
        authorAvatar: 'https://i.pravatar.cc/150?img=3',
        coverImage: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&q=80',
        readTime: '12 min read',
        likes: 4320,
        comments: 201,
        tags: ['AI', 'technology'],
      },
      {
        id: 't2',
        title: 'Why Your Next Laptop Will Have No Fan',
        catchline: 'ARM is winning silently. The age of the passively cooled machine is here.',
        author: 'Sasha Kim',
        authorAvatar: 'https://i.pravatar.cc/150?img=9',
        coverImage: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&q=80',
        readTime: '7 min read',
        likes: 1890,
        comments: 87,
        tags: ['hardware', 'technology'],
      },
      {
        id: 't3',
        title: 'Building a Side Project in 72 Hours',
        catchline: 'Sleep is optional. Scope is negotiable. Shipping is not.',
        author: 'Marco Reyes',
        authorAvatar: 'https://i.pravatar.cc/150?img=15',
        coverImage: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&q=80',
        readTime: '9 min read',
        likes: 2450,
        comments: 134,
        tags: ['dev', 'productivity'],
      },
      {
        id: 't4',
        title: 'The Quiet Death of the Pixel Phone',
        catchline: 'Google\'s hardware ambition vs. the relentless tyranny of average.',
        author: 'Priya Sharma',
        authorAvatar: 'https://i.pravatar.cc/150?img=44',
        coverImage: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&q=80',
        readTime: '6 min read',
        likes: 3100,
        comments: 198,
        tags: ['gadgets', 'technology'],
      },
      {
        id: 't5',
        title: 'Open Source Won. Now What?',
        catchline: 'The revolution happened quietly in a git commit. Here\'s the aftermath.',
        author: 'Leo Chan',
        authorAvatar: 'https://i.pravatar.cc/150?img=56',
        coverImage: 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=600&q=80',
        readTime: '8 min read',
        likes: 5600,
        comments: 267,
        tags: ['opensource', 'technology'],
      },
    ],
  },
  {
    id: 'fashion',
    label: 'Fashion',
    emoji: '✨',
    tagline: 'Dressing up is an act of quiet rebellion',
    icon: 'style',
    bgFrom: '#c75b7a',
    bgTo: '#e8a0b5',
    textColor: '#ffffff',
    posts: [
      {
        id: 'f1',
        title: 'The Return of the Ugly Shoe',
        catchline: 'Comfort is now couture. How chunky soles conquered the runway.',
        author: 'Isabelle Fontaine',
        authorAvatar: 'https://i.pravatar.cc/150?img=25',
        coverImage: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80',
        readTime: '5 min read',
        likes: 2230,
        comments: 119,
        tags: ['fashion', 'shoes'],
      },
      {
        id: 'f2',
        title: 'Grandma\'s Wardrobe Is Trending Again',
        catchline: 'Cardigans, corsages, and the comforting aesthetics of slow fashion.',
        author: 'Mia Bloom',
        authorAvatar: 'https://i.pravatar.cc/150?img=36',
        coverImage: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=600&q=80',
        readTime: '4 min read',
        likes: 1780,
        comments: 93,
        tags: ['fashion', 'vintage'],
      },
      {
        id: 'f3',
        title: 'How Colour Theory Changed My Closet',
        catchline: 'I stopped buying black and started living in ochre. Here\'s the palette.',
        author: 'Zara Ndao',
        authorAvatar: 'https://i.pravatar.cc/150?img=41',
        coverImage: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=600&q=80',
        readTime: '6 min read',
        likes: 3450,
        comments: 176,
        tags: ['fashion', 'style'],
      },
      {
        id: 'f4',
        title: 'Menswear Is Having a Moment',
        catchline: 'Florals for spring? Not just groundbreaking — now unavoidable.',
        author: 'Theo Larsson',
        authorAvatar: 'https://i.pravatar.cc/150?img=52',
        coverImage: 'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=600&q=80',
        readTime: '5 min read',
        likes: 1290,
        comments: 64,
        tags: ['fashion', 'menswear'],
      },
      {
        id: 'f5',
        title: 'The Ethics of Fast Fashion in 2026',
        catchline: 'Who pays the real price for a ten-dollar shirt? A thread worth pulling.',
        author: 'Amara Diallo',
        authorAvatar: 'https://i.pravatar.cc/150?img=60',
        coverImage: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=600&q=80',
        readTime: '10 min read',
        likes: 6700,
        comments: 342,
        tags: ['fashion', 'ethics'],
      },
    ],
  },
  {
    id: 'sports',
    label: 'Sports',
    emoji: '🏆',
    tagline: 'Every victory begins with a story no one believed',
    icon: 'sports_soccer',
    bgFrom: '#5a8f5a',
    bgTo: '#8fbc8f',
    textColor: '#ffffff',
    posts: [
      {
        id: 's1',
        title: 'The Marathon Runner Who Lost Everything and Won Anyway',
        catchline: 'At mile 22, the body is a rumour. What keeps you going is everything else.',
        author: 'Kemi Adeyemi',
        authorAvatar: 'https://i.pravatar.cc/150?img=7',
        coverImage: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=600&q=80',
        readTime: '8 min read',
        likes: 4100,
        comments: 183,
        tags: ['sports', 'running'],
      },
      {
        id: 's2',
        title: 'Football Tactics Explained for People Who Don\'t Watch Football',
        catchline: 'The beautiful game is a chess match played at sprint speed. Here\'s the board.',
        author: 'Rafael Torres',
        authorAvatar: 'https://i.pravatar.cc/150?img=18',
        coverImage: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=600&q=80',
        readTime: '9 min read',
        likes: 2870,
        comments: 124,
        tags: ['sports', 'football'],
      },
      {
        id: 's3',
        title: 'What Pickleball Tells Us About the Future of Sport',
        catchline: 'The fastest growing sport in America is also the most polarising. Make it make sense.',
        author: 'Dana Fox',
        authorAvatar: 'https://i.pravatar.cc/150?img=29',
        coverImage: 'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=600&q=80',
        readTime: '6 min read',
        likes: 1560,
        comments: 79,
        tags: ['sports', 'pickleball'],
      },
      {
        id: 's4',
        title: 'How Sleep Became the New Performance Drug',
        catchline: 'Elite athletes are now sleeping 10 hours a night. The data is impossible to ignore.',
        author: 'Jordan Wells',
        authorAvatar: 'https://i.pravatar.cc/150?img=38',
        coverImage: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=600&q=80',
        readTime: '7 min read',
        likes: 3290,
        comments: 156,
        tags: ['sports', 'performance'],
      },
      {
        id: 's5',
        title: 'The Rise of Women\'s Cricket',
        catchline: 'Stadiums that once held hundreds now hold thousands. The game has changed.',
        author: 'Priya Menon',
        authorAvatar: 'https://i.pravatar.cc/150?img=45',
        coverImage: 'https://images.unsplash.com/photo-1540747913346-19212a4cf528?w=600&q=80',
        readTime: '8 min read',
        likes: 2140,
        comments: 97,
        tags: ['sports', 'cricket'],
      },
    ],
  },
  {
    id: 'health',
    label: 'Health',
    emoji: '🌿',
    tagline: 'Small habits, compounding quietly into a life',
    icon: 'favorite',
    bgFrom: '#3d8b7a',
    bgTo: '#7fc4b5',
    textColor: '#ffffff',
    posts: [
      {
        id: 'h1',
        title: 'The Gut-Brain Axis Nobody Told You About',
        catchline: 'Your stomach has been sending messages to your brain. It\'s time to read them.',
        author: 'Dr. Ananya Roy',
        authorAvatar: 'https://i.pravatar.cc/150?img=5',
        coverImage: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=600&q=80',
        readTime: '11 min read',
        likes: 5800,
        comments: 289,
        tags: ['health', 'gut'],
      },
      {
        id: 'h2',
        title: 'Why I Quit the Gym and Started Walking',
        catchline: 'The most underrated exercise is completely free and requires no subscription.',
        author: 'Sam Osei',
        authorAvatar: 'https://i.pravatar.cc/150?img=14',
        coverImage: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=600&q=80',
        readTime: '5 min read',
        likes: 7200,
        comments: 401,
        tags: ['health', 'fitness'],
      },
      {
        id: 'h3',
        title: 'The Science of a Good Night\'s Sleep',
        catchline: 'Eight hours is a myth. Here\'s what the research actually says.',
        author: 'Claire Dupont',
        authorAvatar: 'https://i.pravatar.cc/150?img=27',
        coverImage: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=600&q=80',
        readTime: '8 min read',
        likes: 4560,
        comments: 213,
        tags: ['health', 'sleep'],
      },
      {
        id: 'h4',
        title: 'Burnout Is Not a Badge of Honour',
        catchline: 'We glorified exhaustion for a decade. The bill has come due.',
        author: 'James Okonkwo',
        authorAvatar: 'https://i.pravatar.cc/150?img=33',
        coverImage: 'https://images.unsplash.com/photo-1499728603263-13726abce5fd?w=600&q=80',
        readTime: '9 min read',
        likes: 9100,
        comments: 512,
        tags: ['health', 'mentalhealth'],
      },
      {
        id: 'h5',
        title: 'Cold Plunges: Trend or Tool?',
        catchline: 'The internet swears by it. The science is more complicated. Here\'s the cold truth.',
        author: 'Nina Larsen',
        authorAvatar: 'https://i.pravatar.cc/150?img=48',
        coverImage: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&q=80',
        readTime: '6 min read',
        likes: 3340,
        comments: 167,
        tags: ['health', 'wellness'],
      },
    ],
  },
  {
    id: 'travel',
    label: 'Travel',
    emoji: '🗺️',
    tagline: 'Getting lost is just another name for discovery',
    icon: 'flight',
    bgFrom: '#d97706',
    bgTo: '#fbbf24',
    textColor: '#ffffff',
    posts: [
      {
        id: 'tr1',
        title: '48 Hours in Tbilisi: A City That Defies Definition',
        catchline: 'Soviet brutalism, medieval towers, and the best khinkali you\'ll ever eat.',
        author: 'Luca Romano',
        authorAvatar: 'https://i.pravatar.cc/150?img=6',
        coverImage: 'https://images.unsplash.com/photo-1565008447742-97f6f38c985c?w=600&q=80',
        readTime: '7 min read',
        likes: 3670,
        comments: 178,
        tags: ['travel', 'Georgia'],
      },
      {
        id: 'tr2',
        title: 'Why I Keep Going Back to Japan',
        catchline: 'A country that makes you feel simultaneously enormous and very small.',
        author: 'Emily Cho',
        authorAvatar: 'https://i.pravatar.cc/150?img=20',
        coverImage: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=600&q=80',
        readTime: '9 min read',
        likes: 8200,
        comments: 443,
        tags: ['travel', 'Japan'],
      },
      {
        id: 'tr3',
        title: 'The Overnight Train as a Way of Life',
        catchline: 'Sleeping across borders. Waking up somewhere new. The romance is real.',
        author: 'Felix Wagner',
        authorAvatar: 'https://i.pravatar.cc/150?img=35',
        coverImage: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=600&q=80',
        readTime: '6 min read',
        likes: 5430,
        comments: 234,
        tags: ['travel', 'trains'],
      },
      {
        id: 'tr4',
        title: 'Solo Travel at 50: What No One Prepares You For',
        catchline: 'It\'s not about being brave. It\'s about being interested in your own company.',
        author: 'Ruth Amara',
        authorAvatar: 'https://i.pravatar.cc/150?img=49',
        coverImage: 'https://images.unsplash.com/photo-1503220317375-aaad61436b1b?w=600&q=80',
        readTime: '8 min read',
        likes: 6780,
        comments: 356,
        tags: ['travel', 'solo'],
      },
      {
        id: 'tr5',
        title: 'Slow Tourism and the Joy of Going Nowhere Fast',
        catchline: 'One town. Two weeks. A thousand things you\'d have missed on a highlights tour.',
        author: 'Hana Müller',
        authorAvatar: 'https://i.pravatar.cc/150?img=63',
        coverImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80',
        readTime: '7 min read',
        likes: 4120,
        comments: 198,
        tags: ['travel', 'slowtravel'],
      },
    ],
  },
  {
    id: 'food',
    label: 'Food',
    emoji: '🍜',
    tagline: 'Every recipe is a letter from someone\'s grandmother',
    icon: 'restaurant',
    bgFrom: '#ea580c',
    bgTo: '#fb923c',
    textColor: '#ffffff',
    posts: [
      {
        id: 'fo1',
        title: 'The Perfect Bowl of Ramen Took Me Three Years',
        catchline: 'Broth is philosophy. Noodles are commitment. Everything else is negotiable.',
        author: 'Yuki Tanaka',
        authorAvatar: 'https://i.pravatar.cc/150?img=4',
        coverImage: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&q=80',
        readTime: '6 min read',
        likes: 5100,
        comments: 243,
        tags: ['food', 'Japanese'],
      },
      {
        id: 'fo2',
        title: 'In Defense of the Humble Egg',
        catchline: 'The most versatile ingredient in any kitchen has been sleeping on itself.',
        author: 'Bea Hartley',
        authorAvatar: 'https://i.pravatar.cc/150?img=22',
        coverImage: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=600&q=80',
        readTime: '4 min read',
        likes: 3890,
        comments: 201,
        tags: ['food', 'cooking'],
      },
      {
        id: 'fo3',
        title: 'What a Lagos Street Market Taught Me About Flavour',
        catchline: 'Suya smoke. Puff-puff oil. The kind of food that changes your palate permanently.',
        author: 'Chika Eze',
        authorAvatar: 'https://i.pravatar.cc/150?img=39',
        coverImage: 'https://images.unsplash.com/photo-1606787366850-de6330128bfc?w=600&q=80',
        readTime: '8 min read',
        likes: 4560,
        comments: 189,
        tags: ['food', 'African'],
      },
      {
        id: 'fo4',
        title: 'The Sourdough Starter I\'ve Kept Alive for 4 Years',
        catchline: 'It has a name. It has a personality. And yes, I worry about it when I travel.',
        author: 'Tom Becker',
        authorAvatar: 'https://i.pravatar.cc/150?img=53',
        coverImage: 'https://images.unsplash.com/photo-1586444248902-2f64eddc13df?w=600&q=80',
        readTime: '7 min read',
        likes: 6230,
        comments: 311,
        tags: ['food', 'baking'],
      },
      {
        id: 'fo5',
        title: 'Why Fermented Food Is Having Its Renaissance',
        catchline: 'Kimchi, kefir, kombucha: the quiet revolution happening in your fridge.',
        author: 'Soo-Jin Park',
        authorAvatar: 'https://i.pravatar.cc/150?img=65',
        coverImage: 'https://images.unsplash.com/photo-1563379091339-03246963d6e4?w=600&q=80',
        readTime: '9 min read',
        likes: 3780,
        comments: 167,
        tags: ['food', 'fermentation'],
      },
    ],
  },
  {
    id: 'science',
    label: 'Science',
    emoji: '🔬',
    tagline: 'Reality is stranger than any story we could invent',
    icon: 'science',
    bgFrom: '#6b5b8a',
    bgTo: '#a093bc',
    textColor: '#ffffff',
    posts: [
      {
        id: 'sc1',
        title: 'The James Webb Images That Broke My Brain',
        catchline: 'We are not looking at the past. We are looking at the past arriving now.',
        author: 'Dr. Alicia Vega',
        authorAvatar: 'https://i.pravatar.cc/150?img=2',
        coverImage: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=600&q=80',
        readTime: '10 min read',
        likes: 11200,
        comments: 589,
        tags: ['science', 'space'],
      },
      {
        id: 'sc2',
        title: 'How Fungi Are Rebuilding the World',
        catchline: 'Underground, a network older than language is quietly repairing ecosystems.',
        author: 'Marcus Green',
        authorAvatar: 'https://i.pravatar.cc/150?img=16',
        coverImage: 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=600&q=80',
        readTime: '8 min read',
        likes: 7800,
        comments: 345,
        tags: ['science', 'biology'],
      },
      {
        id: 'sc3',
        title: 'Quantum Entanglement, Explained Without Metaphors',
        catchline: 'No spooky action at a distance. Just the universe being deeply weird.',
        author: 'Prof. Ingrid Holm',
        authorAvatar: 'https://i.pravatar.cc/150?img=31',
        coverImage: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&q=80',
        readTime: '13 min read',
        likes: 6400,
        comments: 412,
        tags: ['science', 'physics'],
      },
      {
        id: 'sc4',
        title: 'CRISPR and the Question of What We Should Change',
        catchline: 'We can now edit the code of life. The harder question is whether we should.',
        author: 'Dr. Fatima Hassan',
        authorAvatar: 'https://i.pravatar.cc/150?img=43',
        coverImage: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=600&q=80',
        readTime: '11 min read',
        likes: 5200,
        comments: 298,
        tags: ['science', 'genetics'],
      },
      {
        id: 'sc5',
        title: 'The Periodic Table Turned 150. Here\'s What We Still Don\'t Know',
        catchline: 'We named the elements. We didn\'t finish the story.',
        author: 'Ben Okoro',
        authorAvatar: 'https://i.pravatar.cc/150?img=57',
        coverImage: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=600&q=80',
        readTime: '7 min read',
        likes: 3400,
        comments: 156,
        tags: ['science', 'chemistry'],
      },
    ],
  },
  {
    id: 'art',
    label: 'Art & Design',
    emoji: '🎨',
    tagline: 'Making something from nothing is a kind of magic',
    icon: 'palette',
    bgFrom: '#a04668',
    bgTo: '#d48aa6',
    textColor: '#ffffff',
    posts: [
      {
        id: 'a1',
        title: 'Why Brutalism Is the Most Honest Design Movement',
        catchline: 'Concrete doesn\'t lie. Neither does a sans-serif with nothing to hide.',
        author: 'Oliver Graf',
        authorAvatar: 'https://i.pravatar.cc/150?img=8',
        coverImage: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=600&q=80',
        readTime: '7 min read',
        likes: 4300,
        comments: 231,
        tags: ['design', 'architecture'],
      },
      {
        id: 'a2',
        title: 'Learning to Draw at 32 Changed How I See Everything',
        catchline: 'Not to make art. To make myself slow down and actually look.',
        author: 'Suki Watanabe',
        authorAvatar: 'https://i.pravatar.cc/150?img=24',
        coverImage: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&q=80',
        readTime: '6 min read',
        likes: 6800,
        comments: 334,
        tags: ['art', 'drawing'],
      },
      {
        id: 'a3',
        title: 'The Typography That Defined a Decade',
        catchline: 'From Helvetica to variable fonts. How letters became feelings.',
        author: 'Lars Eriksson',
        authorAvatar: 'https://i.pravatar.cc/150?img=37',
        coverImage: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=600&q=80',
        readTime: '8 min read',
        likes: 3900,
        comments: 187,
        tags: ['design', 'typography'],
      },
      {
        id: 'a4',
        title: 'Street Art Is Not Vandalism. It\'s a Conversation.',
        catchline: 'Every city wall is a public canvas. The question is who gets to speak.',
        author: 'Carlos Vidal',
        authorAvatar: 'https://i.pravatar.cc/150?img=50',
        coverImage: 'https://images.unsplash.com/photo-1551913902-c92207136625?w=600&q=80',
        readTime: '5 min read',
        likes: 5100,
        comments: 278,
        tags: ['art', 'streetart'],
      },
      {
        id: 'a5',
        title: 'AI Art and the Question of Authorship',
        catchline: 'Who made this image? The prompt engineer, the model, or the millions who trained it?',
        author: 'Nora Klein',
        authorAvatar: 'https://i.pravatar.cc/150?img=61',
        coverImage: 'https://images.unsplash.com/photo-1686261191785-0ac4a7f22e49?w=600&q=80',
        readTime: '12 min read',
        likes: 8900,
        comments: 567,
        tags: ['art', 'AI'],
      },
    ],
  },
  {
    id: 'fiction',
    label: 'Fiction',
    emoji: '📖',
    tagline: 'The best lies we tell are the ones that reveal the truth',
    icon: 'menu_book',
    bgFrom: '#7a5690',
    bgTo: '#b899c9',
    textColor: '#ffffff',
    posts: [
      {
        id: 'fi1',
        title: 'The Last Lighthouse Keeper',
        catchline: 'She had been sending signals for forty years. Something finally answered.',
        author: 'Evelyn Cross',
        authorAvatar: 'https://i.pravatar.cc/150?img=10',
        coverImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=80',
        readTime: '15 min read',
        likes: 7600,
        comments: 398,
        tags: ['fiction', 'mystery'],
      },
      {
        id: 'fi2',
        title: 'A Robot Walks Into a Philosophy Class',
        catchline: 'It asks the one question the professor has been avoiding for twenty years.',
        author: 'Owen McCarthy',
        authorAvatar: 'https://i.pravatar.cc/150?img=19',
        coverImage: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=600&q=80',
        readTime: '18 min read',
        likes: 5400,
        comments: 289,
        tags: ['fiction', 'scifi'],
      },
      {
        id: 'fi3',
        title: 'The Town That Forgot Its Own Name',
        catchline: 'On the third Tuesday of every month, the street signs go blank.',
        author: 'Isla MacGregor',
        authorAvatar: 'https://i.pravatar.cc/150?img=30',
        coverImage: 'https://images.unsplash.com/photo-1543418219-44e30b057fea?w=600&q=80',
        readTime: '20 min read',
        likes: 6100,
        comments: 312,
        tags: ['fiction', 'magical realism'],
      },
      {
        id: 'fi4',
        title: 'Letters Never Sent',
        catchline: 'She wrote to him every day for a year after he died. Then she started getting replies.',
        author: 'Adaeze Obi',
        authorAvatar: 'https://i.pravatar.cc/150?img=46',
        coverImage: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=600&q=80',
        readTime: '14 min read',
        likes: 9200,
        comments: 478,
        tags: ['fiction', 'romance'],
      },
      {
        id: 'fi5',
        title: 'The Cartographer of Forgotten Places',
        catchline: 'His maps showed cities that had never existed. Tourists kept finding them.',
        author: 'Pierre Delacroix',
        authorAvatar: 'https://i.pravatar.cc/150?img=55',
        coverImage: 'https://images.unsplash.com/photo-1524661135-423995f22d0b?w=600&q=80',
        readTime: '16 min read',
        likes: 4800,
        comments: 234,
        tags: ['fiction', 'fantasy'],
      },
    ],
  },
  {
    id: 'music',
    label: 'Music',
    emoji: '🎵',
    tagline: 'Three minutes to say what a lifetime couldn\'t',
    icon: 'music_note',
    bgFrom: '#b45309',
    bgTo: '#fcd34d',
    textColor: '#ffffff',
    posts: [
      {
        id: 'm1',
        title: 'The Album That Ruined All Other Albums for Me',
        catchline: 'You know the one. The record that reset your ear. Here\'s mine.',
        author: 'Jay Osei',
        authorAvatar: 'https://i.pravatar.cc/150?img=11',
        coverImage: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&q=80',
        readTime: '7 min read',
        likes: 5600,
        comments: 312,
        tags: ['music', 'albums'],
      },
      {
        id: 'm2',
        title: 'Why Jazz Is the Most Democratic Music',
        catchline: 'No conductor. No fixed script. Just a conversation between people who listen.',
        author: 'Miles Addo',
        authorAvatar: 'https://i.pravatar.cc/150?img=23',
        coverImage: 'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=600&q=80',
        readTime: '9 min read',
        likes: 4100,
        comments: 198,
        tags: ['music', 'jazz'],
      },
      {
        id: 'm3',
        title: 'Learning Guitar at 40: A Humbling Education',
        catchline: 'My fingers refused. My ego refused more. Then something clicked.',
        author: 'Sandra Liu',
        authorAvatar: 'https://i.pravatar.cc/150?img=40',
        coverImage: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=600&q=80',
        readTime: '6 min read',
        likes: 6800,
        comments: 389,
        tags: ['music', 'guitar'],
      },
      {
        id: 'm4',
        title: 'The Playlist That Got Me Through the Hardest Year',
        catchline: 'Music as medicine. Tracklist as memoir. Volume as survival.',
        author: 'Tariq Ismail',
        authorAvatar: 'https://i.pravatar.cc/150?img=54',
        coverImage: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&q=80',
        readTime: '5 min read',
        likes: 8900,
        comments: 467,
        tags: ['music', 'personal'],
      },
      {
        id: 'm5',
        title: 'How K-Pop Conquered the Algorithm',
        catchline: 'Fandom as infrastructure. Community as chart strategy. And yes, it works.',
        author: 'Yuna Cho',
        authorAvatar: 'https://i.pravatar.cc/150?img=64',
        coverImage: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&q=80',
        readTime: '10 min read',
        likes: 12400,
        comments: 678,
        tags: ['music', 'Kpop'],
      },
    ],
  },
  {
    id: 'mindfulness',
    label: 'Mindfulness',
    emoji: '🧘',
    tagline: 'The present moment is the only address that matters',
    icon: 'self_improvement',
    bgFrom: '#4a8a7a',
    bgTo: '#7dbfb0',
    textColor: '#ffffff',
    posts: [
      {
        id: 'mi1',
        title: 'I Meditated for 100 Days. Here\'s What Surprised Me.',
        catchline: 'I expected calm. I got clarity. They are not the same thing.',
        author: 'Anita Sharma',
        authorAvatar: 'https://i.pravatar.cc/150?img=1',
        coverImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80',
        readTime: '8 min read',
        likes: 6700,
        comments: 334,
        tags: ['mindfulness', 'meditation'],
      },
      {
        id: 'mi2',
        title: 'Boredom Is Not the Enemy',
        catchline: 'We built a world to fill every gap. Then we forgot what the gaps were for.',
        author: 'Paul Ndiaye',
        authorAvatar: 'https://i.pravatar.cc/150?img=13',
        coverImage: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&q=80',
        readTime: '5 min read',
        likes: 8100,
        comments: 412,
        tags: ['mindfulness', 'slowliving'],
      },
      {
        id: 'mi3',
        title: 'What Forest Bathing Actually Is',
        catchline: 'Shinrin-yoku isn\'t a walk in the woods. It\'s a different relationship with being outdoors.',
        author: 'Keiko Mori',
        authorAvatar: 'https://i.pravatar.cc/150?img=28',
        coverImage: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=600&q=80',
        readTime: '7 min read',
        likes: 5400,
        comments: 267,
        tags: ['mindfulness', 'nature'],
      },
      {
        id: 'mi4',
        title: 'Journaling Rewired My Brain. Literally.',
        catchline: 'The neuroscience of writing by hand in a world of keyboards.',
        author: 'Grace Osei',
        authorAvatar: 'https://i.pravatar.cc/150?img=42',
        coverImage: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=600&q=80',
        readTime: '6 min read',
        likes: 7900,
        comments: 389,
        tags: ['mindfulness', 'journaling'],
      },
      {
        id: 'mi5',
        title: 'On the Art of Doing Nothing Well',
        catchline: 'L\'art de ne rien faire. The Italians call it dolce far niente. We call it guilt.',
        author: 'Sofia Ricci',
        authorAvatar: 'https://i.pravatar.cc/150?img=59',
        coverImage: 'https://images.unsplash.com/photo-1499209974431-9dddcece7f88?w=600&q=80',
        readTime: '5 min read',
        likes: 9800,
        comments: 501,
        tags: ['mindfulness', 'lifestyle'],
      },
    ],
  },
  {
    id: 'film',
    label: 'Film & TV',
    emoji: '🎬',
    tagline: 'Stories that flicker at 24 frames per second',
    icon: 'movie',
    bgFrom: '#4a5568',
    bgTo: '#8a95a5',
    textColor: '#ffffff',
    posts: [
      {
        id: 'fl1',
        title: 'Why Slow Cinema Is the Antidote to Everything',
        catchline: 'Tarkovsky. Akerman. Reygadas. Films that breathe instead of race.',
        author: 'Henri Poirot',
        authorAvatar: 'https://i.pravatar.cc/150?img=17',
        coverImage: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=600&q=80',
        readTime: '11 min read',
        likes: 4200,
        comments: 234,
        tags: ['film', 'cinema'],
      },
      {
        id: 'fl2',
        title: 'The TV Show That Changed How I Understand Grief',
        catchline: 'No spoilers. Just a recommendation that feels like a responsibility.',
        author: 'Maya Oduya',
        authorAvatar: 'https://i.pravatar.cc/150?img=26',
        coverImage: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=600&q=80',
        readTime: '6 min read',
        likes: 9100,
        comments: 512,
        tags: ['TV', 'drama'],
      },
      {
        id: 'fl3',
        title: 'Korean Cinema\'s Decade of Dominance',
        catchline: 'From Parasite to The Glory. How a national cinema became a global obsession.',
        author: 'Jin-Ho Park',
        authorAvatar: 'https://i.pravatar.cc/150?img=34',
        coverImage: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=600&q=80',
        readTime: '9 min read',
        likes: 7800,
        comments: 389,
        tags: ['film', 'Korean'],
      },
      {
        id: 'fl4',
        title: 'The Art of the Movie Score You Never Notice',
        catchline: 'The best film music disappears. Here\'s why that\'s the hardest thing to achieve.',
        author: 'Oscar Muñoz',
        authorAvatar: 'https://i.pravatar.cc/150?img=51',
        coverImage: 'https://images.unsplash.com/photo-1478147427282-58a87a433b70?w=600&q=80',
        readTime: '8 min read',
        likes: 5600,
        comments: 267,
        tags: ['film', 'music'],
      },
      {
        id: 'fl5',
        title: 'Animation Is Not for Children',
        catchline: 'Miyazaki. Satoshi Kon. BoJack Horseman. The medium has always been adult.',
        author: 'Lily Chen',
        authorAvatar: 'https://i.pravatar.cc/150?img=62',
        coverImage: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=600&q=80',
        readTime: '10 min read',
        likes: 8400,
        comments: 445,
        tags: ['film', 'animation'],
      },
    ],
  },
]

export const formatCount = (n = 0) => {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}k`
  return String(n)
}